spring:
  profiles:
    active:
      - dev

---
spring:
  prifiles: dev #开发环境
  application:
    name: microservicecloud-config-atguigu-dev

---    
spring: 
  profiles: test #测试环境
  application:
    name: microservicecould-config-atguigu-test

# 请保存为UTF-8格式